"""empty message

Revision ID: 4875b911c43b
Revises: 
Create Date: 2024-02-09 14:16:30.177357

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision = '4875b911c43b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employee',
    sa.Column('id', mssql.UNIQUEIDENTIFIER(), nullable=False),
    sa.Column('nama', sa.String(), nullable=True),
    sa.Column('alamat', sa.String(), nullable=True),
    sa.Column('foto', sa.String(), nullable=True),
    sa.Column('status_menikah', sa.String(), nullable=True),
    sa.Column('usia', sa.String(), nullable=True),
    sa.Column('telepon', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('updated_id', mssql.UNIQUEIDENTIFIER(), nullable=True),
    sa.Column('deleted_id', mssql.UNIQUEIDENTIFIER(), nullable=True),
    sa.Column('create_at', sa.DateTime(), nullable=True),
    sa.Column('update_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('employee')
    # ### end Alembic commands ###
