"""empty message

Revision ID: 4c110a083fae
Revises: ea7ad0bc83d8
Create Date: 2024-02-09 15:33:14.296036

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4c110a083fae'
down_revision = 'ea7ad0bc83d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.alter_column('nama',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.String(length=250),
               existing_nullable=True)
        batch_op.alter_column('alamat',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.String(length=250),
               existing_nullable=True)
        batch_op.alter_column('status_menikah',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.String(length=250),
               existing_nullable=True)
        batch_op.alter_column('email',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.String(length=250),
               existing_nullable=False)
        batch_op.alter_column('updated_id',
               existing_type=mysql.CHAR(length=1),
               type_=mysql.CHAR(length=250),
               existing_nullable=True)
        batch_op.alter_column('deleted_id',
               existing_type=mysql.CHAR(length=1),
               type_=mysql.CHAR(length=250),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.alter_column('deleted_id',
               existing_type=mysql.CHAR(length=250),
               type_=mysql.CHAR(length=1),
               existing_nullable=True)
        batch_op.alter_column('updated_id',
               existing_type=mysql.CHAR(length=250),
               type_=mysql.CHAR(length=1),
               existing_nullable=True)
        batch_op.alter_column('email',
               existing_type=sa.String(length=250),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=False)
        batch_op.alter_column('status_menikah',
               existing_type=sa.String(length=250),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=True)
        batch_op.alter_column('alamat',
               existing_type=sa.String(length=250),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=True)
        batch_op.alter_column('nama',
               existing_type=sa.String(length=250),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=True)

    # ### end Alembic commands ###
