"""empty message

Revision ID: ea7ad0bc83d8
Revises: 0af3395b3ac4
Create Date: 2024-02-09 15:30:41.253508

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ea7ad0bc83d8'
down_revision = '0af3395b3ac4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=mysql.CHAR(length=36),
               type_=mysql.CHAR(length=250),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=mysql.CHAR(length=250),
               type_=mysql.CHAR(length=36),
               existing_nullable=False)

    # ### end Alembic commands ###
